// Types
export const GET_DEVICES_START = 'GET_DEVICES_START';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAIL = 'GET_DEVICES_FAIL';

export const CREATE_DEVICES_SUCCESS = 'CREATE_DEVICES_SUCCESS';
export const CREATE_DEVICES_FAIL = 'CREATE_DEVICES_FAIL';

export const GET_EDIT_DEVICE = 'GET_EDIT_DEVICE';
export const EDIT_DEVICES_SUCCESS = 'EDIT_DEVICES_SUCCESS';
export const EDIT_DEVICES_FAIL = 'EDIT_DEVICES_FAIL';

export const GET_DEVICE_DELETE = 'GET_DEVICE_DELETE';
export const DELETE_DEVICES_SUCCESS = 'DELETE_DEVICES_SUCCESS';
export const DELETE_DEVICES_FAIL = 'DELETE_DEVICES_FAIL';