// Types
export const GET_ALERTS_START = 'GET_ALERTS_START';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAIL = 'GET_ALERTS_FAIL';

export const SEND_ALERT_START = 'SEND_ALERT_START';
export const GENERATE_ALERT_START = 'GENERATE_ALERT';
export const GENERATE_ALERT_FINISH = 'GENERATE_ALERT_FINISH';
export const SEND_ALERT_SUCCESS = 'SEND_ALERT_SUCCESS';
export const SEND_ALERT_FAIL = 'SEND_ALERT_FAIL';

export const GET_DELETE_ALERT = 'GET_DELETE_ALERT';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAIL = 'DELETE_ALERT_FAIL';

export const GET_ALERT_BY_DEVICE_START = 'GET_ALERT_BY_DEVICE_START';
export const GET_ALERT_BY_DEVICE_SUCCESS = 'GET_ALERT_BY_DEVICE_SUCCESS';
export const GET_ALERT_BY_DEVICE_FAIL = 'GET_ALERT_BY_DEVICE_FAIL';
